# Machine Learning Algorithm
### 2- Simple Linear Regression

### Step 1 - Import Libraries and read The Data

In [44]:
#import Library

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [27]:
# import Your Data
df=pd.read_csv('ml_data_salary.csv')
df.head()

age  distance  YearsExperience  Salary
0  31.1     77.75              1.1   39343
1  31.3     78.25              1.3   46205
2  31.5     78.75              1.5   37731
3  32.0     80.00              2.0   43525
4  32.2     80.50              2.2   39891

### Step 2 - Clean the Data (Data Wragling)

In [45]:
df.isnull().sum()

age                0
distance           0
YearsExperience    0
Salary             0
dtype: int64

## Step 3 - Splitting the Data into Training data and Testing

In [28]:
# Independent Variable
X=df[['age','distance','YearsExperience']]
X.head()

age  distance  YearsExperience
0  31.1     77.75              1.1
1  31.3     78.25              1.3
2  31.5     78.75              1.5
3  32.0     80.00              2.0
4  32.2     80.50              2.2

In [29]:
# Dependent Variable
y=df[['Salary']]
y.head()

Salary
0   39343
1   46205
2   37731
3   43525
4   39891

##  Fit Linear Regression model without traing and testing Phase

In [46]:

# Create the Model and Fit the Model
model=LinearRegression().fit(X,y)
model
# Directly fitting the data without training}

LinearRegression()

In [37]:
# To get the Coefficent of indepen variable
model.coef_

array([[-2.68055892e+15,  1.06092560e+15,  2.82449143e+13]])

In [38]:
# To get the Intercept 
model.intercept_

array([8.4734743e+14])

In [39]:
model.predict([[31.1,77.75,1.1]])

c:\Users\Khan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[36211.]])

## Assignment
  - how to plot multiple Linear Regression
  - how to test the effeciecy of model

In [43]:
reg =LinearRegression().fit(X,y)
model.score(X,y)

0.9569513065723807

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Step 4 
- Fit Linear Regression Model with Traing data

In [55]:
from sklearn.linear_model import  LinearRegression

In [58]:
Multi=LinearRegression().fit(X_train,y_train)
Multi

LinearRegression()

## Step 5 :
   - Plotting Multiple Linear Regression Model

In [76]:
# import matplotlib.pyplot as plt
# plt.scatter(X_test,y_test)

## Step 6
  - Testing or Evating your model

In [73]:
print("The Score of train data:",Multi.score(X_train,y_train)*100)
print("The Score of Test data:",Multi.score(X_test,y_test)*100)

The Score of train data: 94.10595586173315
The Score of Test data: 98.82841419890302


## Step 7 :
 - Prediction of unknown Value

In [64]:
Multi.predict([[31.1,72.75,1.3]])

c:\Users\Khan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[2.63942077e+15]])

In [68]:
from sklearn.metrics import r2_score


y_pred=Multi.predict(X_test)
Accuracy=r2_score(y_test,y_pred)*100
print(" Accuracy of the model is %.2f" %Accuracy)

 Accuracy of the model is 98.83
