In [2]:
import numpy as np

In [8]:


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[0:6:2])

[1 3 5]


In [27]:
b= np.array([1, 2, 3, 4, 5, 6, 7])

print(b[3:6:2])
d=np.array(['faizan','asif','shahid'])
d

[4 6]


array(['faizan', 'asif', 'shahid'], dtype='<U6')

In [29]:
c=b.astype('f')
c

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [37]:
c

array([34.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=float32)

In [35]:
d=c.view()
d[0]=34
d

array([34.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=float32)

In [36]:
c

array([34.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=float32)

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [50]:
q=np.arange(9).reshape(3,3)
q

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
w=np.arange(9).reshape(3,3)
w

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
e=np.column_stack((q,w))
e

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [93]:
three=np.array([[[
    2,3],[7,8]],[[5,6],[7,8]],[[9,0],[1,2]]
])
three

array([[[2, 3],
        [7, 8]],

       [[5, 6],
        [7, 8]],

       [[9, 0],
        [1, 2]]])

In [101]:
b=np.array([0,1,2,3,4,5,6,7,8])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [98]:
b.ndim

1

In [100]:
b=b[np.newaxis,:]
b

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8]]])

In [89]:
three.size

12

In [90]:
three.shape

(3, 2, 2)

In [91]:
three.ndim

3