In [1]:
import numpy as np

In [2]:


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[0:6:2])

[1 3 5]


In [4]:
b= np.array([1, 2, 3, 4, 5, 6, 7])

print(b[3:6:2])
d=np.array(['faizan','asif','shahid'])
d

[4 6]


array(['faizan', 'asif', 'shahid'], dtype='<U6')

In [5]:
c=b.astype('f')
c

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [6]:
c

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [7]:
d=c.view()
d[0]=34
d

array([34.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=float32)

In [8]:
c

array([34.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=float32)

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
q=np.arange(9).reshape(3,3)
q

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
w=np.arange(9).reshape(3,3)
w

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
e=np.column_stack((q,w))
e

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [13]:
three=np.array([[[
    2,3],[7,8]],[[5,6],[7,8]],[[9,0],[1,2]]
])
three

array([[[2, 3],
        [7, 8]],

       [[5, 6],
        [7, 8]],

       [[9, 0],
        [1, 2]]])

In [14]:
b=np.array([0,1,2,3,4,5,6,7,8])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
b.ndim

1

In [16]:
b=b[np.newaxis,:]
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [17]:
three.size

12

In [18]:
three.shape

(3, 2, 2)

In [19]:
three.ndim

3

- Join to  array

In [31]:

arr1 = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2=np.array([[7,8,9],[10,12,13]])
arr2

array([[ 7,  8,  9],
       [10, 12, 13]])

In [33]:
join=np.concatenate((arr1,arr2))
join

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])

- Split a array

In [37]:
# print("\n",arr1)
# print("\n",arr2)
join


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])

In [47]:
split = np.array_split(arr1,3)
split

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]