# Importing a Numpy Library

In [2]:
import numpy as np

# This One Dimentional Array


In [3]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [5]:
c=np.ones(3)
c

array([1., 1., 1.])

In [6]:
d=np.empty(3)
d

array([1., 1., 1.])

In [10]:
d[0]=12
d

array([12.,  1.,  1.])

# Create array with Arange function

In [86]:
d=np.arange(8)
d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [96]:
# With specified range
d=np.arange(0,10,2)
d

array([0, 2, 4, 6, 8])

In [98]:

d=np.linspace(0,10,num=4)
d

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [89]:

d=np.arange(2,8,2)
d

array([2, 4, 6])

In [102]:
withdatatype=np.arange(10,dtype=np.float64)
withdatatype

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [90]:
print(a[0:])

[1 2 3 4 5]


# length of Array

In [69]:
l=len(a)
print(l)

2


# 2-Dimentional array

In [113]:
d2=np.array([[1,2],[3,4],[5,6]])
d2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
d3=np.zeros((3,4))
d3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 3-Dimentional array

In [112]:
c=np.arange(24).reshape(3,2,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [23]:
b=np.array(["samosas","sd","fsad","Fasd","sdsa"])
b

array(['samosas', 'sd', 'fsad', 'Fasd', 'sdsa'], dtype='<U7')

In [24]:
c=np.concatenate((a,b))
c

array(['1', '2', '3', '4', '5', 'samosas', 'sd', 'fsad', 'Fasd', 'sdsa'],
      dtype='<U11')

In [26]:
c.sort()
c

array(['1', '2', '3', '4', '5', 'Fasd', 'fsad', 'samosas', 'sd', 'sdsa'],
      dtype='<U11')